#!/usr/bin/env python3
"""Apply the aggregate evidence budget while all host output is still private.

This is intentionally content-blind: priority/status/size metadata decides what is
kept. Low-priority raw files that cannot fit are deleted before redaction, reducing
both redaction work and the amount of sensitive material held during the run.
"""
from __future__ import annotations
import argparse, json
from pathlib import Path

from recordio import read_records, write_records


def main() -> int:
    ap=argparse.ArgumentParser()
    ap.add_argument('--stage',required=True)
    ap.add_argument('--budget',required=True,type=int)
    a=ap.parse_args()
    stage=Path(a.stage).resolve(); collectors=stage/'collectors'; evidence_root=(stage/'evidence').resolve()
    candidates=[]; all_rows=[]; before=0
    for cdir in sorted((p for p in collectors.iterdir() if p.is_dir()),key=lambda p:p.name) if collectors.exists() else []:
        apath=cdir/'artifacts.records'; rows=read_records(apath,'artifacts'); all_rows.append((apath,rows))
        for row in rows:
            label=str(row.get('label',''))
            # Labels are generated by safe_name. Reject anything that could escape
            # its collector evidence directory rather than trusting host-derived data.
            if not label or '/' in label or label in ('.','..'): continue
            path=(evidence_root/cdir.name/f'{label}.txt').resolve()
            if evidence_root not in path.parents or not path.is_file(): continue
            size=path.stat().st_size; before += size
            issue=(not bool(row.get('accepted',False))) or bool(row.get('timed_out')) or bool(row.get('truncated'))
            priority=int(row.get('priority',50) or 50)
            candidates.append((issue,priority,size,str(row.get('id','')),row,path))
    candidates.sort(key=lambda x:(-int(x[0]),-x[1],x[2],x[3]))
    used=0; omitted=[]
    budget=max(0,a.budget)
    for issue,priority,size,aid,row,path in candidates:
        if used+size <= budget:
            used += size; continue
        row['omitted_reason']='evidence_budget_pre_redaction'
        row['omitted_bytes']=size
        omitted.append([aid,size,priority])
        path.unlink(missing_ok=True)
    for apath,rows in all_rows: write_records(apath,'artifacts',rows)
    report={'schema':'linux-context-prune','version':2,'budget_bytes':budget,'captured_bytes_before_budget':before,'retained_bytes_before_redaction':used,'omitted_files':len(omitted),'omitted_bytes':sum(x[1] for x in omitted)}
    (stage/'meta').mkdir(parents=True,exist_ok=True)
    (stage/'meta'/'prune.json').write_text(json.dumps(report,separators=(',',':'))+'\n',encoding='utf-8')
    return 0

if __name__=='__main__': raise SystemExit(main())
